sonar.projectKey=awful-studio
sonar.projectName=AWFUL STUDIO
sonar.sources=extension,tools
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.exclusions=historical/**,dist/**,.blender/**,preview/storybook-static/**
